window.PORTFOLIO_PROJECTS = [
    {
        id: "huggingface-agents",
        file: "huggingfaceagents.html",
        title: "Creating Multi-Agent Systems with SmolAgents - Huggingface Course",
        navLabel: "Multi-Agent Systems w/ SmolAgents",
        navGroup: "personal",
        navOrder: 1,
        category: "AI/ML",
        indexOrder: 1,
        terminalDescription: "Multi-agent systems with SmolAgents",
        highlight: {
            order: 1,
            date: "July, 2025",
            tags: ["agentic-AI", "llms", "huggingface", "certification"],
            description: `I recently successfully completed the full certification from the <a href="https://huggingface.co/learn/agents-course/unit0/introduction" target="_blank" rel="noopener noreferrer">Hugging Face AI Agents Course</a>. As the final project of this course, I created a multi-agent system using <a href="https://huggingface.co/docs/smolagents/en/index" target="_blank" rel="noopener noreferrer">SmolAgents</a> to solve complex agentic reasoning problems from the GAIA dataset. Ultimately, through extensive system design, testing, and prompt engineering, I was able to achieve a 55% success rate on the required subset of the GAIA dataset (passing was 30%)!`,
            caption: "AI generated using gpt-4o",
            image: {
                source: "images/multiagent.png",
                generated: "multiagent",
                widths: [480, 800],
                width: 1536,
                height: 1024,
                alt: "Illustration of several AI agents collaborating",
            },
        },
    },
    {
        id: "wildlife-analyzer",
        file: "wildlifeanalyzer.html",
        title: "Wildlife Analyzer - An MLOps Dashboard for Wildlife Observations",
        navLabel: "Wildlife Analyzer",
        navGroup: "personal",
        navOrder: 2,
        category: "AI/ML",
        indexOrder: 2,
        terminalDescription: "MLOps dashboard for wildlife observations",
        highlight: {
            order: 2,
            date: "June, 2025",
            tags: ["mlops", "Python", "CI/CD", "Streamlit"],
            description: `An MLOps-style pipeline and dashboard for analyzing wildlife observations. This project leverages the <a href="https://api.inaturalist.org/v1/docs/" target="_blank" rel="noopener noreferrer">iNaturalist API</a>, and incorporates a variety of tools and techniques including LLMs, clustering, data visualization, and logging/monitoring via MLflow and AWS S3.`,
            caption: "AI generated using gpt-4o",
            image: {
                source: "images/moose-analysis.png",
                generated: "moose-analysis",
                widths: [480, 800],
                width: 1536,
                height: 1024,
                alt: "Illustration of a scientist analyzing a moose observation",
            },
        },
    },
    {
        id: "mmo",
        file: "mmo.html",
        title: "MMO - Multimodal Multi-agent Organization & Benchmarking",
        highlightTitle: "MMO - Multi-modal Multi-agent Organization & Robust Benchmarking",
        navLabel: "MMO - MLLM Benchmarking",
        navGroup: "school",
        navOrder: 1,
        category: "AI/ML",
        indexOrder: 5,
        terminalDescription: "Multimodal multi-agent organization and benchmarking",
        highlight: {
            order: 4,
            date: "December 18, 2024",
            tags: ["llms", "mllms", "benchmarking", "Python"],
            description: "Course research project for CMSC848K - Multimodal Foundation Models. Developed a multi-modal multi-agent system and investigated how to improve multimodal large language model (MLLM) benchmarking.",
            caption: "AI generated using DALL-E",
            image: {
                source: "images/mllm.webp",
                generated: "mllm",
                widths: [480, 800],
                width: 1024,
                height: 1024,
                alt: "Illustration representing multimodal language models",
            },
        },
    },
    {
        id: "disney-brdf",
        file: "disneybrdf.html",
        title: "Monte Carlo Rendering and Disney BRDF in PyTorch",
        navLabel: "Disney BRDF & Monte Carlo Rendering in PyTorch",
        navGroup: "school",
        navOrder: 2,
        category: "Computer Graphics",
        indexOrder: 1,
        terminalDescription: "Physically based rendering research",
        highlight: {
            order: 5,
            date: "December 14, 2024",
            tags: ["computer-graphics", "PyTorch", "monte-carlo", "path-tracing"],
            description: `An implementation of Monte Carlo path tracing and <a href="https://media.disneyanimation.com/uploads/production/publication_asset/48/asset/s2012_pbs_disney_brdf_notes_v3.pdf" target="_blank" rel="noopener noreferrer">Disney "principled" BRDF</a> in PyTorch. An extension of an assignment codebase from CMSC740 - Advanced Graphics course. Implemented advanced computer graphics concepts such as Monte Carlo integration, neural radiosity, and multiple importance sampling. As a final project, I also implemented the Disney shading system in the existing renderer with fine-grained control of object appearance using 10 parameters.`,
            caption: "Two spheres with Disney style shading!",
            image: {
                source: "images/disneythumbnail.png",
                generated: "disneythumbnail",
                widths: [480],
                width: 596,
                height: 452,
                alt: "Two rendered spheres demonstrating Disney BRDF materials",
            },
        },
    },
    {
        id: "personal-rag",
        file: "personalrag.html",
        title: "Personal RAG Quiz System",
        highlightTitle: "Personalized RAG Quiz System using OpenAI Structured Outputs",
        navLabel: "RAG Quiz",
        navGroup: "personal",
        navOrder: 3,
        category: "AI/ML",
        indexOrder: 6,
        terminalDescription: "Personal retrieval-augmented generation",
        highlight: {
            order: 6,
            date: "May, 2024",
            tags: ["llms", "structured-outputs", "retrieval-augmented-generation", "web-scraping"],
            description: "A demonstration of using retrieval augmented generation and structured outputs through OpenAI API. Exploring how AI can be used to help us learn, automatically creating and testing us on custom uploaded knowledge from documents and webpages.",
            caption: "AI generated using DALL-E",
            image: {
                source: "images/learning.webp",
                generated: "learning",
                widths: [480, 800],
                width: 1024,
                height: 1024,
                alt: "Illustration of personalized learning with AI",
            },
        },
    },
    {
        id: "video-generation",
        file: "videogen.html",
        title: "Improving Control and Consistency of Diffusion-Generated Video",
        navLabel: "Consistent Video Generation",
        navGroup: "school",
        navOrder: 4,
        category: "AI/ML",
        indexOrder: 7,
        terminalDescription: "Controllable diffusion-generated video",
        highlight: {
            order: 7,
            date: "May 2, 2024",
            tags: ["deep-learning", "stable-diffusion", "controlnet", "video-gen"],
            description: "Semester-long course project created for CMSC720: Foundations of Deep Learning. Investigated state of the art diffusion-based video generation methods, and experimented with various approaches to improving their quality in terms of consistency and controllability. Wrote and submitted a NEURIPS format paper for a mock-conference within our class.",
            caption: "Selected frames from a video I generated",
            image: {
                source: "images/jeep1.png",
                generated: "jeep1",
                widths: [480, 800],
                width: 986,
                height: 274,
                alt: "Three generated frames of a Jeep driving through snow",
            },
        },
    },
    {
        id: "virtual-classroom",
        file: "vrclass.html",
        title: "Virtual Classroom - Interactive Education in VR",
        highlightTitle: "Virtual Classroom",
        navLabel: "XR Education",
        navGroup: "school",
        navOrder: 5,
        category: "HCI",
        indexOrder: 2,
        terminalDescription: "XR learning environment",
        highlight: {
            order: 8,
            date: "May 17, 2024",
            tags: ["AR/VR", "Unity", "c#", "education", "user-study"],
            description: "This is a virtual reality (VR) project created in the Unity game engine throughout the Spring 2024 semester for the course CMSC838C: Advances in XR. I led a group of 5 classmates to design a virtual classroom environment, and we conducted a user study to investigate the benefits of XR education over traditional remote learning mediums such as video.",
            caption: "A scene from our VR vector math lecture",
            image: {
                source: "images/vectordemo1.png",
                generated: "vectordemo1",
                widths: [480],
                width: 728,
                height: 440,
                alt: "Virtual reality lesson demonstrating vector mathematics",
            },
        },
    },
    {
        id: "art-advisor",
        file: "artadvisor.html",
        title: "AI Art Advisor",
        navLabel: "AI Art Advisor",
        navGroup: "personal",
        navOrder: 4,
        category: "AI/ML",
        indexOrder: 8,
        terminalDescription: "AI-powered feedback for visual art",
    },
    {
        id: "magical-pet",
        file: "magicalpet.html",
        title: "MagicalPet - A Friendly Desktop AI Assistant",
        navLabel: "MagicalPet - A Desktop AI Assistant",
        navGroup: "school",
        navOrder: 3,
        category: "HCI",
        indexOrder: 1,
        terminalDescription: "Interactive AI character experience",
    },
    {
        id: "emd",
        file: "emd.html",
        title: "Accessibility of Touch Screens for Elderly",
        navLabel: "Accessibility of Touch Screens for Elderly",
        navGroup: "school",
        navOrder: 6,
        category: "HCI",
        indexOrder: 3,
        terminalDescription: "Research on touchscreen accessibility for older adults",
    },
];

window.PORTFOLIO_FEATURED_ENTRIES = [
    {
        id: "agentic-data-analysis",
        title: "Understanding Agentic AI Systems for Data Analysis: Techniques, Components, and Considerations",
        href: "documents/Understanding_Agentic_AI_Systems_for_Data_Analysis.pdf",
        category: "AI/ML",
        indexOrder: 3,
        external: true,
        highlight: {
            order: 3,
            date: "May, 2025",
            tags: ["agentic-AI", "llms", "data-analysis", "research"],
            description: `A survey paper exploring state of the art agentic AI systems for data analysis. In this work I also provide an overview of the most common LLM-based approaches to general workflows, and also propose a component framework for understanding agentic AI systems inspired by <a href="https://books.google.com/books/about/The_Project_Management_Life_Cycle.html?id=YuGoUW3ZeP8C" target="_blank" rel="noopener noreferrer">The Project Management Lifecycle</a>.`,
            caption: "AI generated using gpt-4o",
            image: {
                source: "images/agenticdataanalysis.png",
                generated: "agenticdataanalysis",
                widths: [480, 800],
                width: 1024,
                height: 1024,
                alt: "Illustration representing agentic AI data analysis",
            },
        },
    },
    {
        id: "llm-spatial-layout",
        title: "LLM Spatial Layouts from Image Descriptions",
        href: "https://github.com/simoncwang/LLMSpatialLayout",
        category: "AI/ML",
        indexOrder: 4,
        external: true,
    },
];
