const fs = require("node:fs");
const path = require("node:path");
const { root } = require("./site-files");

const modules = [
    "base.css",
    "homepage.css",
    "navigation.css",
    "projects.css",
    "footer.css",
    "playground.css",
    "content.css",
    "responsive.css",
    "effects.css",
];

function buildCss() {
    const content = modules.map((file) => {
        const css = fs.readFileSync(path.join(root, "styles", file), "utf8").trim();
        return `/* styles/${file} */\n${css}`;
    }).join("\n\n");

    return `/* Generated by npm run css:build. Edit files in styles/. */\n${content}\n`
        .replaceAll('url("../fonts/', 'url("./fonts/')
        .replaceAll("url('../assets/", "url('./assets/");
}

module.exports = { buildCss, modules };
